apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-talk-static-html
  labels:
    app: k3s-talk-static-html
spec:
  selector:
    matchLabels:
      app: k3s-talk-static-html
  template:
    metadata:
      labels:
        app: k3s-talk-static-html
    spec:
      containers:
      - name: static-html
        image: plod/k3s-talk-static-html:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
--- 
apiVersion: v1
kind: Service
metadata:
  name: static
  labels:
     app: k3s-talk-static-html
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 80
  selector:
     app: k3s-talk-static-html
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: static-ingress
spec:
  rules:
  - host: talk.pi4.plod.tv
    http:
      paths:
      - path: /
        backend:
          serviceName: static
          servicePort: 8080
