apiVersion: v1
kind: Service
metadata:
  name: inlets
  labels:
    talk: starting-k8s-with-k3s-on-pi
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    talk: starting-k8s-with-k3s-on-pi
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: ingress
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/custom-response-headers: Access-Control-Allow-Origin:*
spec:
  rules:
  - host: hello-world.pi4.plod.tv
    http:
      paths:
      - path: /
        backend:
          serviceName: inlets
          servicePort: 8080
